#!/bin/sh

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2011-present Alex@ELEC (http://alexelec.in.ua)

URL="$@"

echo "*** IPTV stream TVLINK: $URL ***" >&2
/usr/bin/cvlc --quiet --ipv4-timeout=5000 --network-caching=0 --no-drop-late-frames --no-skip-frames "$URL" --sout-mux-caching=0 --sout '#std{mux=ts,access=file,dst=-}'
